name: Issue Logger (Vulnerable Version)

on:
  issues:
    types: [opened]

jobs:
  log-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Log issue title
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
        run: |
          echo "New issue title is $ISSUE_TITLE"

